Agrega documentación
IslasGECI/bootstrapping_tools pull request #10
Opened 2022-02-02 20:49 UTC by islasfernando

2022-02-09 16:32 UTC, devarops requested changes
Aquí te dejo una revisón rápida. 😉

2022-02-09 16:32 UTC, devarops commented on .github/workflows/main.yml
> +
No necesitamos estas líneas vacías:

```suggestion 
```

2022-02-09 16:32 UTC, devarops commented on bootstrapping_tools/bootstrapping.py
> +    """This function represent a simple power lay of the type: f(y) = a*x^y
¿Será _law_ en lugar de _lay_?
```suggestion
    """This function represent a simple power law of the type: f(y) = a*x^y
```

2022-02-09 16:32 UTC, devarops commented on bootstrapping_tools/bootstrapping.py
> +    """This function removes outliers from distribution using the standard deviation and a range
Creo que el _"This function"_ sale sobrando:

```suggestion
    """Remove outliers from distribution using the standard deviation and a range
```

2022-02-09 16:32 UTC, devarops commented on bootstrapping_tools/bootstrapping.py
> +    """This function filters an array using Tukey fences method
Creo que el _"This function"_ sale sobrando:

```suggestion
    """Filter an array using Tukey fences method
```

2022-02-09 16:32 UTC, devarops commented on bootstrapping_tools/bootstrapping.py
> +    """Function to select method to filter the outliers in data.
Creo que el _"Function"_ sale sobrando:

```suggestion
    """Select method to filter the outliers in data.
```

2022-02-10 18:30 UTC, xwalls approved these changes
Excelente Trabajo!
Somos concientes de los mutantes restantes pero esos quedan para un futuro PR
![image](https://user-images.githubusercontent.com/9456708/153473328-0db165d8-2d90-4986-a837-2d067b945da8.png)

![Image of Yaktocat](https://media.giphy.com/media/tIeCLkB8geYtW/giphy.gif)

2022-02-10 22:59 UTC, merged